name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: password
          POSTGRES_DB: flaskdb
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U admin" --health-timeout=30s --health-retries=3
      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest
    - name: Build Docker Image
      run: docker build -t my-python-app .
      
    - name: Deploy to Heroku
      uses: akshnz/heroku-action@v0.1
      with:
        heroku_app_name: 'your-heroku-app-name'
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
